version: "3"

networks:
  backend:

volumes:
  restheart-datadb:

services:
  nginx:
    container_name: nginx-proxy
    depends_on:
      - restheart
      - mongodb
    volumes:
      - $PWD:/etc/nginx/conf.d
    ports:
      - "443:443"
    image: nginx:1.21
    networks:
      - backend

  restheart:
    image: softinstigate/restheart:6.0.3
    container_name: restheart
    depends_on:
      - mongodb
    networks:
      - backend
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:4.4
    container_name: restheart-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: restheart
      MONGO_INITDB_ROOT_PASSWORD: R3ste4rt!
    command: --bind_ip_all --auth
    networks:
      - backend
