version: "3"

services:
  nginx:
    container_name: nginx-proxy
    depends_on:
      - restheart
      - mongodb
    volumes:
      - $PWD:/etc/nginx/conf.d
    ports:
      - "443:443"
    image: nginx:1.21

  restheart:
    image: softinstigate/restheart:6.3
    environment:
      MONGO_URI: mongodb://mongodb
    command: ["--envFile", "/opt/restheart/etc/default.properties"]
    depends_on:
      - mongodb
      - mongodb-init

  mongodb:
    image: mongo:5.0
    command: ["--bind_ip_all", "--replSet", "rs0"]

  ### Initialize MongoDB as a single node Replica Set
  mongodb-init:
    image: mongo:5.0
    depends_on:
      - mongodb
    entrypoint: >-
      bash -c "for i in {1..10}; do mongo --host mongodb --eval 
      'if (!rs.status().ok) rs.initiate();' && break || sleep 3; done"
